### ISSUE TITLE
missing flag icons on android

### ISSUE THREAD

**Issue by Chris1234567899** [Salvatore-Giordano/CountryCodePicker#6]
I too have the problem that some icons are not shown (some others are). This was on Android 5.1, I guess that the device I have (Lenovo Vibe K5) is not supporting some fonts.

Maybe there is the chance to combine this package with this one? https://pub.dartlang.org/packages/country_icons

![imagen](https://user-images.githubusercontent.com/12623865/42105267-5804c45c-7b95-11e8-8c13-4adc7e312ab1.png)

**Comment by Salvatore-Giordano** [comment]
Oh, ok I see. I'll try this package asap. Thank you very much

**Comment by mmcc007** [comment]
I checked out the new images feature using:
```
  country_code_picker:
    git:
      url: git@github.com:Salvatore-Giordano/CountryCodePicker.git
      ref: 79a90ce
```
and I can confirm it worked on a real ios device 👍
